services:
  - type: web
    name: my-app
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.9.0  # Specify the Node.js version you want to use